package usst.web.entity;

import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.sql.Timestamp;

@Getter
@Setter
public class Advertisement implements Serializable {
    private Integer adId;
    private String adName;
    private String adImageUrl; // New field to store the image URL
    private String adUrl; // Now generated by the system
    private String adFeature;
    private Timestamp adStartTime;
    private Timestamp adEndTime;
    private Byte adUse;
}
